# Generated by Django 4.2.6 on 2023-10-09 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("unit", models.CharField(max_length=250)),
                ("quantity", models.IntegerField()),
                ("availabilityDate", models.DateTimeField()),
                ("productImg", models.ImageField(upload_to="product_images/")),
                (
                    "farmer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("views", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
