# Generated by Django 4.2.6 on 2023-10-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.CharField(max_length=300)),
                ("publishedDate", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
                    ),
                ),
            ],
        ),
    ]
