# Generated by Django 4.2.6 on 2023-10-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="farmer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
            ),
        ),
    ]
